from sqlalchemy import Column, Integer, String, DateTime, ForeignKey, JSON
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.db.session import Base


class BusinessAnalysis(Base):
    """
    SQLAlchemy model representing the 'business_analysis' table.
    Stores structured outputs generated by the Business Understanding AI Agent.
    Strictly linked 1-to-1 with a Business record (business_id is unique).
    """
    __tablename__ = "business_analysis"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    business_id = Column(
        Integer,
        ForeignKey("businesses.id", ondelete="CASCADE"),
        unique=True,
        nullable=False,
        index=True,
        comment="Referenced business ID (1-to-1)",
    )
    business_category = Column(
        String(255),
        nullable=False,
        comment="Identified industry/domain category (e.g., Food & Beverage)",
    )
    business_subcategory = Column(
        String(255),
        nullable=False,
        comment="Specific niche subcategory (e.g., Quick-Service Specialty Cafe)",
    )
    business_model = Column(
        String(255),
        nullable=False,
        comment="Monetization and delivery structure (e.g., Brick-and-mortar Retail + Takeaway)",
    )
    target_customers = Column(
        JSON,
        nullable=False,
        default=list,
        comment="List of primary and secondary customer segments",
    )
    products_or_services = Column(
        JSON,
        nullable=False,
        default=list,
        comment="List of core offerings extracted or inferred from business concept",
    )
    required_resources = Column(
        JSON,
        nullable=False,
        default=list,
        comment="List of fundamental assets, labor, and capital equipment required",
    )
    operational_requirements = Column(
        JSON,
        nullable=False,
        default=list,
        comment="Key day-to-day processes, licensing, and workflow prerequisites",
    )
    potential_risks = Column(
        JSON,
        nullable=False,
        default=list,
        comment="Identified operational, market, or regulatory risks",
    )
    recommended_analysis = Column(
        JSON,
        nullable=False,
        default=list,
        comment="Recommended specialized downstream analyses (Location, Competitor, Financial, etc.)",
    )
    created_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    # Relationship back to the parent Business model
    business = relationship("Business", back_populates="analysis")

    def __repr__(self):
        return f"<BusinessAnalysis id={self.id} business_id={self.business_id} category='{self.business_category}'>"
