"""
Curated Business & Regulatory Knowledge Documents.
Provides authoritative, verified knowledge across startup fundamentals,
MSME government schemes, GST/taxation, FSSAI regulations, unit economics,
retail benchmarks, and manufacturing setup.
"""

KNOWLEDGE_DOCUMENTS = [
    {
        "doc_id": "startup-fundamentals-01",
        "title": "Startup Fundamentals & Business Viability Framework",
        "category": "Startup Fundamentals",
        "date": "2024-01-15",
        "license": "Open Educational Resource",
        "source": "Open Entrepreneurship Knowledge Base",
        "content": """
A viable business requires product-market fit, sustainable unit economics, and operational feasibility.
Key metrics for initial feasibility include:
1. Customer Acquisition Cost (CAC): Total marketing expenditure divided by new customers acquired.
2. Lifetime Value (LTV): Gross profit generated by a customer over their entire relationship. Target LTV:CAC ratio is at least 3:1.
3. Contribution Margin: Revenue minus variable costs per unit. Must sufficiently cover fixed overheads.
4. Break-even Horizon: Typical small enterprises aim for operating break-even within 3 to 9 months, and full capital investment recovery within 18 to 36 months.
5. Working Capital Reserve: Standard safety buffer requires maintaining at least 3 to 6 months of operating expenses in liquid reserve.
"""
    },
    {
        "doc_id": "msme-compliance-02",
        "title": "MSME Registration, Classification & Government Schemes",
        "category": "MSME & Compliance",
        "date": "2024-02-01",
        "license": "Public Domain / Government Portal Reference",
        "source": "Ministry of MSME Guidelines",
        "content": """
MSME Classification Thresholds:
- Micro Enterprise: Investment in plant & machinery <= $120,000 (INR 1 Crore) and turnover <= $600,000 (INR 5 Crore).
- Small Enterprise: Investment <= $1.2 Million (INR 10 Crore) and turnover <= $6 Million (INR 50 Crore).
- Medium Enterprise: Investment <= $6 Million (INR 50 Crore) and turnover <= $30 Million (INR 250 Crore).

Registration & Subsidies:
1. Udyam Registration is a 100% free paperless online registration offering priority sector lending, collateral-free credit guarantees (CGTMSE), and electricity tariff concessions.
2. PMEGP (Prime Minister's Employment Generation Programme) provides margin money subsidies of 15% to 35% on project costs for new micro-enterprises.
3. Credit Guarantee Fund Trust for Micro and Small Enterprises (CGTMSE) provides credit guarantees up to INR 2 to 5 Crore without third-party collateral.
"""
    },
    {
        "doc_id": "gst-tax-03",
        "title": "GST Structure, Business Licensing & Tax Compliance",
        "category": "Tax & Legal Compliance",
        "date": "2024-02-10",
        "license": "Public Regulatory Reference",
        "source": "GST & Commercial Tax Council Reference",
        "content": """
General Tax & Registration Requirements for New Businesses:
1. GST Registration: Mandatory if annual turnover exceeds statutory thresholds (goods: INR 40 Lakhs / services: INR 20 Lakhs; lower for special category states) or for inter-state e-commerce supply.
2. Composition Scheme: Small businesses with turnover up to INR 1.5 Crore can pay a flat concession tax (1% for manufacturers/traders, 5% for restaurants) with minimal quarterly compliance.
3. Local Municipal Trade License: Required from municipal corporation to establish physical commercial operations.
4. Shops & Establishments Act: Mandatory registration within 30 days of commencing commercial operations, regulating working hours, employee welfare, and holidays.
5. PAN / TAN / Bank Current Account: Mandatory for corporate transactions and TDS deductions.
"""
    },
    {
        "doc_id": "restaurant-ops-04",
        "title": "Food & Beverage (Restaurant / Cafe) Operations & Standards",
        "category": "Restaurant & F&B",
        "date": "2024-03-01",
        "license": "Open Industry Benchmark",
        "source": "National Restaurant Association Operational Guidelines & FSSAI Standards",
        "content": """
Food & Beverage Operational Benchmarks:
1. Food Cost (COGS): Target 28% - 35% of gross revenue for profitable operations.
2. Prime Cost (COGS + Labor): Should remain below 60% of total revenue.
3. Occupancy / Rent: Ideally 6% - 10% of monthly projected revenue; exceeding 12% creates severe solvency risk.
4. FSSAI License: Mandatory for all food business operators (Basic Registration for turnover < INR 12 Lakhs; State License for INR 12 Lakhs - 20 Crore).
5. Kitchen Equipment Layout: Segregate receiving, dry storage, cold storage, prep area, cooking line, plating, and dishwashing stations to eliminate cross-contamination.
6. Waste Management: Grease traps and organic composting agreements are required by municipal health inspectors.
"""
    },
    {
        "doc_id": "retail-store-05",
        "title": "Retail Store Economics, Footfall Conversion & Inventory Turns",
        "category": "Retail & Commerce",
        "date": "2024-03-15",
        "license": "Open Industry Standard",
        "source": "Retail Operations Best Practices Framework",
        "content": """
Key Drivers of Brick-and-Mortar Retail Success:
1. Footfall & Conversion Rate: Typical walk-in conversion rate is 15% - 25%. High-visibility frontage increases impulse visits by 40%.
2. Sales Per Square Foot (SPSF): Primary metric to evaluate floor plan efficiency and rent feasibility.
3. Inventory Turnover Ratio: Cost of Goods Sold divided by Average Inventory. Health retail benchmark is 4x to 8x turns per year.
4. Shrinkage & Loss Prevention: Average retail shrinkage accounts for 1.2% - 1.8% of inventory value; electronic inventory tracking (RFID/POS barcode) is vital.
5. Gross Margin Return on Investment (GMROI): (Gross Margin % x Sales) / Average Inventory Cost. Benchmark > 2.0 indicates strong product profitability.
"""
    },
    {
        "doc_id": "water-plant-manufacturing-06",
        "title": "Packaged Drinking Water & Mineral Water Plant Setup Requirements",
        "category": "Manufacturing & Utilities",
        "date": "2024-04-01",
        "license": "Industrial Standards Guide",
        "source": "Bureau of Indian Standards (BIS) IS 14543 & FSSAI Guidelines",
        "content": """
Packaged Drinking Water Plant Feasibility & Compliance:
1. BIS Certification (ISI Mark): Compulsory under IS 14543 for packaged drinking water and IS 13428 for natural mineral water.
2. Ground Water Authority NOC: Mandatory clearance from Central Ground Water Authority (CGWA) or State Ground Water Department before boring.
3. Water Treatment Hierarchy: Raw Water Storage -> Sand Filter -> Activated Carbon Filter -> Micron Filters (5μ & 1μ) -> Reverse Osmosis (RO) Membrane -> UV Disinfection -> Ozone Generator -> Final Mineral Dosing.
4. In-House Micro-Biology Lab: Mandatory requirement for BIS approval, including laminar airflow, autoclave, incubators, and full-time qualified microbiologist/chemist.
5. Bottle Blowing & Automatic Rinser-Filler-Capper (RFC) Machine: Standard capacity ranges from 24 BPM to 120+ BPM.
"""
    },
    {
        "doc_id": "marketing-growth-07",
        "title": "Omnichannel Marketing, Local SEO & Customer Acquisition Playbook",
        "category": "Marketing & Distribution",
        "date": "2024-04-20",
        "license": "Open Marketing Benchmark",
        "source": "Digital & Local Commerce Growth Playbook",
        "content": """
Go-To-Market & Growth Architecture:
1. Google Business Profile & Local SEO: Optimize NAP (Name, Address, Phone), collect 50+ genuine customer reviews within 60 days, and list on OpenStreetMap / Apple Maps.
2. Hyperlocal Geo-Fenced Ads: Meta & Google Ads targeting 3-5 km perimeter around exact business location achieve highest ROAS for local retail and restaurants.
3. B2B Corporate Outreach: Establish institutional tie-ups with nearby tech parks, offices, schools, and hospitals with tiered volume discounts.
4. Referral & Loyalty Loops: Point-based reward programs generate 28% higher repeat visit frequency compared to one-off discounts.
5. Platform Aggregators vs Direct Ordering: Utilize aggregators (Zomato/Swiggy/Amazon) for initial discovery while incentivizing direct ordering to protect margin.
"""
    },
    {
        "doc_id": "financial-modeling-08",
        "title": "Financial Projections, Sensitivity Analysis & Working Capital",
        "category": "Financial Management",
        "date": "2024-05-01",
        "license": "Open Financial Modeling Framework",
        "source": "Corporate Finance Institute & Small Business Administration",
        "content": """
Standard Financial Projections for Business Feasibility:
1. Capital Expenditure (CapEx): One-time setup costs including lease deposit, interior build-out, machinery, licenses, and initial inventory.
2. Operating Expenditure (OpEx): Ongoing monthly expenses including rent, salaries, utilities, marketing, maintenance, and insurance.
3. Gross Margin: (Revenue - COGS) / Revenue * 100.
4. Net Profit Margin: (Operating Income - Taxes - Interest - Depreciation) / Revenue * 100.
5. Break-even Analysis: Fixed Costs / (Selling Price per Unit - Variable Cost per Unit).
6. Sensitivity Modeling: Projections should evaluate 3 scenarios: Conservative (70% revenue target), Base (100% target), and Optimistic (130% target with scale efficiencies).
"""
    }
]
